Update sdf2yaml for TA2 error analysis
isi-vista/kairos-yaml pull request #1
Opened 2022-05-27 15:12 UTC by lichtefeld

This has ended up being nearly a complete rewrite. As we're doing a lossy conversion for view-ability I'm dropping some TA2 fields that we don't particularly find interesting right now. If this script were going to be improved we'd probably want to move fields into our `private_data` rather than dropping them?

Also, this should be reviewed but not merged in case there are still change requests made for the viewable results.

2022-05-27 17:04 UTC, aphedges requested changes
Just from looking at the code, there don't seem to be a large amount of structural issues. However, there are a lot of smaller problems I noticed.

2022-05-27 17:04 UTC, aphedges commented on sdf/sdf2yaml.py
> +) -> Sequence[Before]:
The docstring is missing. The precommit checks should have caught this.

2022-05-27 17:04 UTC, aphedges commented on sdf/sdf2yaml.py
> +        if relation.relationPredicate == "wd:Q79030196":
Please add a comment with the qnode's label.

2022-05-27 17:04 UTC, aphedges commented on sdf/sdf2yaml.py
> +    return [edges[edge] for edge in reduced.edges]
This should probably be sorted before it's returned because I'm not sure if `nx.transitive_reduction` is deterministic and it's probably more effort to figure out than to add sorting. If you know it's deterministic, then don't worry about it.

2022-05-27 17:14 UTC, aphedges commented on sdf/sdf2yaml.py
> +                                )
Weird. I definitely suggest trying it again because I might be remembering SDF wrong.

2022-05-27 17:14 UTC, lichtefeld commented on sdf/sdf2yaml.py
> +        sdf_library = Library(**json_data)
Nifty!

2022-05-27 17:25 UTC, lichtefeld commented on sdf/sdf2yaml.py
> +    return [edges[edge] for edge in reduced.edges]
Everything iterated over for edges & nodes should be `dicts` internally so this should be deterministic but I don't think networkx makes any determinism guarantees. In short, I'll sort to ensure determinism.

2022-05-27 17:26 UTC, aphedges commented on sdf/sdf2yaml.py
> +    return [edges[edge] for edge in reduced.edges]
That's a very good point! Unless the edge dictionary is being completely rewritten, sorting here doesn't matter. Any nondeterminism in which edges are removed would be more difficult to fix and wouldn't be solved by sorting. You probably shouldn't bother, then.

2022-05-27 17:48 UTC, lichtefeld commented on sdf/sdf2yaml.py
> +                                )
Your implementation works (I wasn't reassigning to the `participant.values` but rather a new local variable, so maybe that's why?.) Anyway I'm not going to spend any time investigating the weirdness.

2022-06-03 02:40 UTC, aphedges requested changes
I agree with the changes in `Precommit updates`, but the commit message should be improved. In addition, it doesn't really belong in this PR and should probably just be committed directly to `main`.

2022-06-03 02:40 UTC, aphedges commented on sdf/sdf2yaml.py
> +        qnode = qnode.rsplit(":", maxsplit=1)[-1]  # type: ignore
You should be able to remove this `# type: ignore` and the later ones if you `assert isinstance(qnode, str)` right before this line.

2022-06-03 02:40 UTC, aphedges commented on sdf/sdf2yaml.py
> +class PopulateStepReturn:
Because it has no functions, it might make sense for this to be a `namedtuple` instead of a `dataclass` for slightly better performance. It doesn't really matter, though.

2022-06-03 02:40 UTC, aphedges commented on sdf/sdf2yaml.py
> +                print(ref_parts)
Is this debugging code that you accidentally left in? If not, you should add some sort of label for the output so it's clear what's being displayed.

2022-06-03 02:40 UTC, aphedges commented on sdf/sdf2yaml.py
> +                "predicted_g_count": steps_return.predicted_only_count,
I assume these shouldn't have the same value?

2022-06-03 22:09 UTC, aphedges commented
On second thought, you should probably keep the `# type: ignore` comments for now. We might be able to remove them in the future when mypy can handle them. They are a lot easier to automatically detect and remove than asserts.

2022-06-06 15:51 UTC, lichtefeld commented on sdf/sdf2yaml.py
> +class PopulateStepReturn:
I had that thought as well, but just reused `dataclass` given I'd already used it previously in this file.

2022-06-15 17:13 UTC, aphedges requested changes
Please break the formatting changes to `yaml2sdf.py` into a separate commit. I'd appreciate if you could drop the changes to `setup.py` because I have a branch that refactors those lines, anyway.

2022-06-15 19:56 UTC, aphedges requested changes
I cherry-picked your formatting commit onto `main` and finished up the `setup.py` refactoring I first started months ago. Please rebase against `main` and add this script to the entry points for consistency with the other two.

2022-06-15 20:10 UTC, aphedges requested changes
Just some minor stylistic changes left.

2022-06-15 20:10 UTC, aphedges commented on sdf/sdf2yaml.py
The version number should be removed because it's inaccurate and it will be annoying to update.

2022-06-15 20:10 UTC, aphedges commented on sdf/sdf2yaml.py
> +            qlabel_display = f"TA2: {event.ta2qlabel[0] if not isinstance(event.ta2qlabel, str) else event.ta2qlabel} [TA1: {event.qlabel[0] if not isinstance(event.qlabel, str) else event.qlabel}]"
These lines are very long and have some duplicated content. Please refactor them some.

2022-06-15 20:10 UTC, aphedges commented on sdf/sdf2yaml.py
> +            f"Graph G: {steps_return.g_only_count} | Matched: {steps_return.matched_count} | Predicted: {steps_return.predicted_only_count}"
This line is very long and should be wrapped.

2022-06-15 20:20 UTC, aphedges requested changes
Great! It looks all good to me! Once you've squashed the commits, I'll merge it when I'm ready.

2022-06-15 20:24 UTC, aphedges approved these changes
Looks good to me!

2022-06-15 20:25 UTC, merged